# Makefile generated by /usr/bin/verse

PERL5LIB :=

build: theme/slick/assets/site.css
	rm -rf htdocs
	./bin/verse build

rebuild:
	rm -rf htdocs
	./bin/verse build

SASS_SRC := theme/slick/src/slick.sass
SASS_SRC += theme/slick/src/local.sass
SASS_SRC += theme/slick/src/overrides.sass
theme/slick/assets/site.css: $(SASS_SRC)
	sassc theme/slick/src/slick.sass > $@.new
	mv $@.new $@

demo: build
	./bin/verse run

staging:
	cf push -f cf/manifest-stage.yml
prod:
	cf push -f cf/manifest.yml

.PHONY: build rebuild demo staging prod
