#!/bin/bash
set -eu


header() {
	echo "#########################################"
	echo
	echo $*
	echo
	echo "#########################################"
	echo
	echo
}

header "Installing some helpful utilities..."
apt-get update && apt-get install -y curl

curl -L -o /usr/bin/spruce https://github.com/geofffranks/spruce/releases/download/v1.18.2/spruce-linux-amd64
chmod 0755 /usr/bin/spruce

curl -L -o /usr/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
chmod 0755 /usr/bin/jq

VERSION=$(cat releases/version)
CURRENT_VERSION=$(spruce json $REPO_ROOT/data/releases | jq -r .latest)
RELEASE="https://github.com/starkandwayne/shield/releases/tag/$(cat releases/tag)"
BASE_DIR=$(pwd)

if [[ "$CURRENT_VERSION" != "$VERSION" ]]; then
	header "Getting New Release Notes for SHIELD v$VERSION"
	cat releases/body
	(
		spruce json $REPO_ROOT/data/releases | jq -r '{"all":.all}' | spruce merge -
		echo "- notes: |"
		cat releases/body | sed -e 's/^/    /'
		echo
		echo "  url:     $RELEASE"
		echo "  version: $VERSION"
		echo "latest:  $VERSION"
	) | spruce json | jq -r . > $REPO_ROOT/data/releases.tmp
	mv $REPO_ROOT/data/releases.tmp $REPO_ROOT/data/releases
fi

header "Building Docs"
pushd shield-checked-out
	cpan -i -T Text::Markdown < /dev/null
	./bin/mkdocs --version $VERSION \
		--docroot /docs/$VERSION \
		--output $BASE_DIR/$REPO_ROOT/docs/$VERSION \
	&& rm -rf $BASE_DIR/$REPO_ROOT/docs/latest \
	&& cp -a $BASE_DIR/$REPO_ROOT/docs/$VERSION \
			 $BASE_DIR/$REPO_ROOT/docs/latest
popd

header "Re-building Website Static Assets"
pushd $REPO_ROOT
	make
popd

if [[ -n "$(cd ${REPO_ROOT}; git status --porcelain)" ]]; then
	pushd ${REPO_ROOT}

	if [[ -z $(git config --global user.email) ]]; then
		git config --global user.email "ci@starkandwayne.com"
	fi
	if [[ -z $(git config --global user.name) ]]; then
		git config --global user.name "CI Bot"
	fi

	git merge --no-edit ${BRANCH}
	git add -A
	git status
	if [[ "$CURRENT_VERSION" != "$VERSION" ]]; then
		git commit -m "[ci] Integrate release notes from SHIELD v$VERSION"
	else
		git commit -m "[ci] Rebuilt static assets via pipeline"
	fi
	popd
fi
cp -a ${REPO_ROOT} ${REPO_OUT}

echo "DONE"
