#!/bin/bash
set -eu


header() {
	echo "#########################################"
	echo
	echo $*
	echo
	echo "#########################################"
	echo
	echo
}

VERSION=$(cat releases/version)
CURRENT_VERSION=$(spruce json $REPO_ROOT/data/releases | jq -r .latest)
RELEASE="https://github.com/starkandwayne/shield/releases/tag/$(cat releases/tag)"

if [[ "$CURRENT_VERSION" != "$VERSION" ]]; then
	header "Getting New Release Notes for SHIELD v$VERSION"
	cat releases/body
	(
		spruce json $REPO_ROOT/data/releases | jq -r '{"all":.all}' | spruce merge -
		echo "- notes: |"
		cat releases/body | sed -e 's/^/    /'
		echo
		echo "  url:     $RELEASE"
		echo "  version: $VERSION"
		echo "latest:  $VERSION"
	) | spruce json | jq -r . > $REPO_ROOT/data/releases.tmp
	mv $REPO_ROOT/data/releases.tmp $REPO_ROOT/data/releases
fi

header "Re-building Website Static Assets"
pushd $REPO_ROOT
	make
popd

if [[ -n "$(cd ${REPO_ROOT}; git status --porcelain)" ]]; then
	pushd ${REPO_ROOT}

	if [[ -z $(git config --global user.email) ]]; then
		git config --global user.email "ci@starkandwayne.com"
	fi
	if [[ -z $(git config --global user.name) ]]; then
		git config --global user.name "CI Bot"
	fi

	git merge --no-edit ${BRANCH}
	git add -A
	git status
	if [[ "$CURRENT_VERSION" != "$VERSION" ]]; then
		git commit -m "[ci] Integrate release notes from SHIELD v$VERSION"
	else
		git commit -m "[ci] Rebuilt static assets via pipeline"
	fi
	popd
fi
cp -a ${REPO_ROOT} ${REPO_OUT}

echo "DONE"
