#!/bin/bash

set -eu

header "Publishing staging.shieldproject.io"
pushd git
	cf api $CF_API_URL
	cf auth $CF_USERNAME "$CF_PASSWORD"
	cf target -o $CF_ORG -s $CF_SPACE
	cf push -f manifest-stage.yml
popd