#!/usr/bin/perl

use warnings;
use strict;

use Verse qw/verse/;
use Verse::Theme;
use Verse::Object::Page;
use File::Find;
use List::Util qw/max/;
use JSON::PP qw/decode_json/;

dir "{site}";
copy "{theme}/assets/*"  if exist "{theme}/assets";
copy "{root}/content/*"  if exist "{root}/content";

if (exist "{root}/docs") {
	#render { _attrs => { body => '{{CONTENT}}' } },
	render(Verse::Object::Page->parse("---\n--- |-\n{{CONTENT}}"),
		using  => 'docs.tt',
		at     => "{root}/docs.tpl");
	copy "{root}/docs";

	open my $in, "<", path("{root}/docs.tpl")
		or die "docs.tpl: $!\n";
	my $tpl = do { local $/; <$in>; };
	close $in;
	unlink path("{root}/docs.tpl");

	find sub {
		return unless m/\.html$/;
		print "[wrap] $File::Find::name\n";
		open my $in, "<", $_
			or die "$File::Find::name: $!\n";
		my $html = do { local $/; <$in>; };
		close $in;

		open my $out, ">", $_
			or die "$File::Find::name: $!\n";
		my $content = $tpl;
		$content =~ s/\{\{CONTENT}}/$html/;
		print $out $content;
		close $out;
	}, path("{site}/docs/");
}

my @blog = reverse
	sort { ($a->{__dated} || 0) cmp ($b->{__dated} || 0) }
	grep { !$_->attrs->{draft} } blog->read_all;
$_->{timestamp} = $_->{__dated} for @blog;

for my $page (page->read_all) {
	render [$page, { articles => [@blog] }],
		using  => $page->attrs->{template} || "page.tt",
		layout => $page->attrs->{layout}   || "page.tt",
		at     => "{site}/".$page->attrs->{url};
}

open my $fh, "<", "data/releases"
	or die "Unable to read data/releases: $!\n";
my $releases = decode_json(do { local $/; <$fh> });
close $fh;

sub v {
	my ($v) = @_;
	my ($maj, $min, $rev) = split /\./, $v;
	return ($maj * 1000 * 1000)
	     + ($min * 1000)
	     +  $rev;
}

$_->{notes} =~ s/^#/###/gm for @{$releases->{all}};
$releases->{all} = [sort { v($b->{version}) cmp v($a->{version}) } @{$releases->{all}}];
render $releases,
	using  => 'download.tt',
	at     => "{site}/download/index.html";

1;
